name: Release

on: 
  release:
    types:
      - published

jobs:
  release:
    name: Publish GitHub and Cocoapods release
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_13.0.app

      - name: Build
        run: |
          swift build -c release --arch arm64 --arch x86_64
          cp ./.build/apple/Products/Release/figma-export ./Release/figma-export
          zip -r figma-export.zip Release LICENSE

      - name: "Upload assets to a release"
        run: gh release upload ${{ github.event.release.tag_name }} figma-export.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push FigmaExport.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

      - name: Update Homebrew formulae
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: figma-export
          formula-path: figma-export.rb
          homebrew-tap: RedMadRobot/homebrew-formulae
          base-branch: master
          tag-name: ${{ github.event.release.tag_name }}
          download-url: https://github.com/RedMadRobot/figma-export/releases/download/${{ github.event.release.tag_name }}/figma-export.zip
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
